version: '3.9'

services:
  reputation:
    build:
      context: ./app/reputation_service
    container_name: reputation_container
    command: python reputation.py
    ports:
      - "8081:8081"

  web:
    build:
      context: ./app/web_app
    container_name: web_container
    command: python web.py
    ports:
      - "8082:8082"

  influx:
    build:
      context: ./app/DB_service
    container_name: db_container
    command: python influxservice.py
    ports:
      - "8083:8083"

  catalog:
    build:
      context: ./app/catalog_service
    container_name: catalog_container
    command: python catalog2.py
    ports:
      - "8084:8084"

  telegram_bot:
    build:
      context: ./telegram_bot
    container_name: telegram_bot
    command: python bot.py
    ports:
      - "8085:8085"